apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.name }}
  labels:
    app: {{ .Values.global.name }}
  namespace: {{ index .Values.global.clusterNamespace .Values.global.env }}
spec:
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.global.name }}

