apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-network-policy
  namespace: {{ index .Values.global.clusterNamespace .Values.global.env }}
spec:
  podSelector:
    matchLabels:
         app: nginx

